version: "3.9"

services:
  webapp:
    build:
      context: .
    restart: always
    working_dir: /webapp
    networks:
      - wyatt
    volumes:
      - "./webapp:/webapp"
    ports:
      - "3000:3000"

networks:
  wyatt: